#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 12 00:11:01 2021

@author: kaouther
"""

import os
import glob
import pandas as pd
import re

#get working directory
wd =  os.getcwd()
#go to desired files 
os.getcwd()
#select all the files with the extension w want 
file_extension = '.csv'
all_filenames = [i for i in glob.glob(f"*{file_extension}")]

#replace the columns name

for f in all_filenames:
    df = pd.read_csv(f)
    
    for column in df.columns:
        if column == 'Mean_mean':
            df =df.rename(columns={column: 'mean_baseline'})
    
        else:                       
            match = re.search('Mean_\d.*', column)
            if match:
                print(column) 
                found = match.group()
                df = df.rename(columns={column: 'mean_condition'})
                
        df.to_csv(f, index=False, encoding='utf-8-sig')
    
#concat the dataframes
combined_csv = pd.concat([pd.read_csv(f) for f in all_filenames ])
#export 

combined_csv.to_csv( "combined_csv.csv", index=False, encoding='utf-8-sig')

